export enum NODE_TYPES {
  hud = 'hud',
  hudLink = 'hud-link',
  image = 'image',
  imageLink = 'image-link',
  light = 'light',
  lightLink = 'light-link',
  object = 'object',
  objectLink = 'object-link',
  objectHud = 'object-hud',
  objectHudLink = 'object-hud_link',
  objectGroup = 'object-group',
  objectGroupLink = 'object-group_link',
  video = 'video',
  videoLink = 'video-link',
  camera = 'camera',
  configuration = 'configuration',
  folder = 'folder',
  javascript = 'script',
}
