name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: Release new version
        run: npm run release

      - name: Build package
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: bundled-package
          path: dist

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundled-package

      - name: Display structure of downloaded files
        run: ls -R
      # - uses: fregante/setup-git-user@v1
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 12
      #     registry-url: https://npm.pkg.github.com/
      # - run: npm ci

      # - name: Release new version
      #   run: npm run release

      # - name: Build package
      #   run: npm run build

      # - name: Deploy package
      #   run: npm publish
      #   working-directory: dist
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Push changes
      #   run: git push
